package com.online.mall.dto.param;

import java.util.Date;

public class AdminParam {
    /**
     * Database Column Remarks:
     *   管理员登陆名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.login_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   md5加密的密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.password
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String password;
    /**
     * Database Column Remarks:
     *   管理员真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_name
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String adminName;

    /**
     * Database Column Remarks:
     *   证件类型：1 身份证,2军官证,3护照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.identity_card_type
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Byte identityCardType;

    /**
     * Database Column Remarks:
     *   证件号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.identity_card_no
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String identityCardNo;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.mobile_phone
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Integer mobilePhone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_email
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String adminEmail;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.gender
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String gender;

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public Byte getIdentityCardType() {
        return identityCardType;
    }

    public void setIdentityCardType(Byte identityCardType) {
        this.identityCardType = identityCardType;
    }

    public String getIdentityCardNo() {
        return identityCardNo;
    }

    public void setIdentityCardNo(String identityCardNo) {
        this.identityCardNo = identityCardNo;
    }

    public Integer getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(Integer mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }
}
