package com.online.mall.mapper;

import com.online.mall.dto.AdminRoleRelation;
import com.online.mall.dto.AdminRoleRelationExample;
import com.online.mall.dto.RoleInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AdminRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    long countByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByPrimaryKey(Long adminRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insert(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insertSelective(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    List<AdminRoleRelation> selectByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    AdminRoleRelation selectByPrimaryKey(Long adminRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminRoleRelation record, @Param("example") AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExample(@Param("record") AdminRoleRelation record, @Param("example") AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKeySelective(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKey(AdminRoleRelation record);

    @Select("select * from admin_role_relation where admin_id = #{0}")
    List<Integer> selectRoleListByAdminId(Long adminId);

    @Delete("delete  from admin_role_relation where admin_id = #{0}")
    void deleteByAdminId(Long adminId);


    @Select("select b.* from admin_role_relation a inner " +
            "join role_info b on a.role_id = b.role_id where a.admin_id = #{0}")
    List<RoleInfo> getRolesByAdminId(Integer adminId);
}