package com.online.mall.mapper;

import com.online.mall.dto.AdminInf;
import com.online.mall.dto.AdminInfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


public interface AdminInfMapper {

    /**
     * 根据管理员姓名查找
     * */
    AdminInf selectByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    long countByExample(AdminInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByExample(AdminInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByPrimaryKey(Integer adminInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insert(AdminInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insertSelective(AdminInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    List<AdminInf> selectByExample(AdminInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    AdminInf selectByPrimaryKey(Integer adminInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminInf record, @Param("example") AdminInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExample(@Param("record") AdminInf record, @Param("example") AdminInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(AdminInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKey(AdminInf record);
}