package com.online.mall.mapper;

import com.online.mall.dto.AdminLogin;
import com.online.mall.dto.AdminLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    long countByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int deleteByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int insert(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int insertSelective(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    List<AdminLogin> selectByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    AdminLogin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminLogin record, @Param("example") AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByExample(@Param("record") AdminLogin record, @Param("example") AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByPrimaryKeySelective(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByPrimaryKey(AdminLogin record);

    AdminLogin findAdminByUserName(String username);
}