package com.online.mall.mapper;

import com.online.mall.dto.CustomerBalanceLog;
import com.online.mall.dto.CustomerBalanceLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerBalanceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    long countByExample(CustomerBalanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByExample(CustomerBalanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByPrimaryKey(Integer balanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insert(CustomerBalanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insertSelective(CustomerBalanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    List<CustomerBalanceLog> selectByExample(CustomerBalanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    CustomerBalanceLog selectByPrimaryKey(Integer balanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerBalanceLog record, @Param("example") CustomerBalanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExample(@Param("record") CustomerBalanceLog record, @Param("example") CustomerBalanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerBalanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_balance_log
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKey(CustomerBalanceLog record);
}