package com.online.mall.mapper;

import com.online.mall.dto.CustomerLoginLog;
import com.online.mall.dto.CustomerLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    long countByExample(CustomerLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int deleteByExample(CustomerLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int insert(CustomerLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int insertSelective(CustomerLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    List<CustomerLoginLog> selectByExample(CustomerLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    CustomerLoginLog selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerLoginLog record, @Param("example") CustomerLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByExample(@Param("record") CustomerLoginLog record, @Param("example") CustomerLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_log
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByPrimaryKey(CustomerLoginLog record);
}