package com.online.mall.mapper;

import com.online.mall.dto.CustomerPointLog;
import com.online.mall.dto.CustomerPointLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerPointLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    long countByExample(CustomerPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int deleteByExample(CustomerPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int deleteByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int insert(CustomerPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int insertSelective(CustomerPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    List<CustomerPointLog> selectByExample(CustomerPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    CustomerPointLog selectByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerPointLog record, @Param("example") CustomerPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByExample(@Param("record") CustomerPointLog record, @Param("example") CustomerPointLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_point_log
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    int updateByPrimaryKey(CustomerPointLog record);
}