package com.online.mall.mapper;

import com.online.mall.dto.CustomerLevelInf;
import com.online.mall.dto.CustomerLevelInfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerLevelInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    long countByExample(CustomerLevelInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByExample(CustomerLevelInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int deleteByPrimaryKey(Byte customerLevel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insert(CustomerLevelInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int insertSelective(CustomerLevelInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    List<CustomerLevelInf> selectByExample(CustomerLevelInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    CustomerLevelInf selectByPrimaryKey(Byte customerLevel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerLevelInf record, @Param("example") CustomerLevelInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByExample(@Param("record") CustomerLevelInf record, @Param("example") CustomerLevelInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerLevelInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_level_inf
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    int updateByPrimaryKey(CustomerLevelInf record);
}