package com.online.mall.mapper;

import com.online.mall.dto.CustomerLogin;
import com.online.mall.dto.CustomerLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    long countByExample(CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int deleteByExample(CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int insert(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int insertSelective(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    List<CustomerLogin> selectByExample(CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    CustomerLogin selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerLogin record, @Param("example") CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByExample(@Param("record") CustomerLogin record, @Param("example") CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    int updateByPrimaryKey(CustomerLogin record);
}