package com.online.mall.mapper;

import com.online.mall.dto.OrderCustomerAddr;
import com.online.mall.dto.OrderCustomerAddrExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderCustomerAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    long countByExample(OrderCustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByExample(OrderCustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByPrimaryKey(Integer customerAddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insert(OrderCustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insertSelective(OrderCustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    List<OrderCustomerAddr> selectByExample(OrderCustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    OrderCustomerAddr selectByPrimaryKey(Integer customerAddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderCustomerAddr record, @Param("example") OrderCustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExample(@Param("record") OrderCustomerAddr record, @Param("example") OrderCustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKeySelective(OrderCustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_customer_addr
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKey(OrderCustomerAddr record);
}