package com.online.mall.mapper;

import com.online.mall.dto.PermissionInfo;
import com.online.mall.dto.PermissionInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface PermissionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    long countByExample(PermissionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByExample(PermissionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insert(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insertSelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    List<PermissionInfo> selectByExample(PermissionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    PermissionInfo selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") PermissionInfo record, @Param("example") PermissionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExample(@Param("record") PermissionInfo record, @Param("example") PermissionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKeySelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKey(PermissionInfo record);
}