package com.online.mall.mapper;

import com.online.mall.dto.ProductPicInfo;
import com.online.mall.dto.ProductPicInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface ProductPicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    long countByExample(ProductPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByExample(ProductPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByPrimaryKey(Integer productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insert(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insertSelective(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    List<ProductPicInfo> selectByExample(ProductPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    ProductPicInfo selectByPrimaryKey(Integer productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductPicInfo record, @Param("example") ProductPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExample(@Param("record") ProductPicInfo record, @Param("example") ProductPicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKeySelective(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKey(ProductPicInfo record);
}