package com.online.mall.mapper;

import com.online.mall.dto.WarehouseInfo;
import com.online.mall.dto.WarehouseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarehouseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    long countByExample(WarehouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByExample(WarehouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int deleteByPrimaryKey(Short wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insert(WarehouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int insertSelective(WarehouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    List<WarehouseInfo> selectByExample(WarehouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    WarehouseInfo selectByPrimaryKey(Short wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") WarehouseInfo record, @Param("example") WarehouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByExample(@Param("record") WarehouseInfo record, @Param("example") WarehouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKeySelective(WarehouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    int updateByPrimaryKey(WarehouseInfo record);
}