package com.online.mall.dto;

import org.springframework.boot.autoconfigure.kafka.KafkaProperties;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;

/**
 * Database Table Remarks:
 *   管理员登陆表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin_login
 */
public class AdminLogin implements Serializable, UserDetails {
    /**
     * Database Column Remarks:
     *   管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Integer adminId;

    /**
     * Database Column Remarks:
     *   管理员登陆名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.login_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   md5加密的密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.password
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String password;

    /**
     * Database Column Remarks:
     *   管理员状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.user_stats
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Byte userStats;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private static final long serialVersionUID = 1L;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.admin_id
     *
     * @return the value of admin_login.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.admin_id
     *
     * @param adminId the value for admin_login.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.login_name
     *
     * @return the value of admin_login.login_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.login_name
     *
     * @param loginName the value for admin_login.login_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.password
     *
     * @return the value of admin_login.password
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getPassword() {
        return password;
    }

    @Override
    public String getUsername() {
        return null;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return false;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return false;
    }

    @Override
    public boolean isEnabled() {
        return false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.password
     *
     * @param password the value for admin_login.password
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.user_stats
     *
     * @return the value of admin_login.user_stats
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Byte getUserStats() {
        return userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.user_stats
     *
     * @param userStats the value for admin_login.user_stats
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setUserStats(Byte userStats) {
        this.userStats = userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.modified_time
     *
     * @return the value of admin_login.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.modified_time
     *
     * @param modifiedTime the value for admin_login.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminId=").append(adminId);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", userStats=").append(userStats);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}