package com.online.mall.dto;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   管理员和角色关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin_role_relation
 */
public class AdminRoleRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_relation.admin_role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Long adminRoleId;

    /**
     * Database Column Remarks:
     *   管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_relation.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Long adminId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_relation.role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_relation.admin_role_id
     *
     * @return the value of admin_role_relation.admin_role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Long getAdminRoleId() {
        return adminRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_relation.admin_role_id
     *
     * @param adminRoleId the value for admin_role_relation.admin_role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setAdminRoleId(Long adminRoleId) {
        this.adminRoleId = adminRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_relation.admin_id
     *
     * @return the value of admin_role_relation.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_relation.admin_id
     *
     * @param adminId the value for admin_role_relation.admin_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_relation.role_id
     *
     * @return the value of admin_role_relation.role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_relation.role_id
     *
     * @param roleId the value for admin_role_relation.role_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminRoleId=").append(adminRoleId);
        sb.append(", adminId=").append(adminId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}