package com.online.mall.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_info
 */
public class CustomerInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_info_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Integer customerInfoId;

    /**
     * Database Column Remarks:
     *   customer_login表的自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   用户真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   证件类型：1 身份证,2军官证,3护照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.identity_card_type
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Byte identityCardType;

    /**
     * Database Column Remarks:
     *   证件号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.identity_card_no
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String identityCardNo;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.mobile_phone
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Integer mobilePhone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_email
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String customerEmail;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.gender
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   用户积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.user_point
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Integer userPoint;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.register_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Date registerTime;

    /**
     * Database Column Remarks:
     *   会员生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.birthday
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   会员级别:1普通会员,2青铜会员,3白银会员,4黄金会员,5钻石会员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_level
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Byte customerLevel;

    /**
     * Database Column Remarks:
     *   用户余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.user_money
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private BigDecimal userMoney;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_info
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_info_id
     *
     * @return the value of customer_info.customer_info_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Integer getCustomerInfoId() {
        return customerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_info_id
     *
     * @param customerInfoId the value for customer_info.customer_info_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setCustomerInfoId(Integer customerInfoId) {
        this.customerInfoId = customerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_id
     *
     * @return the value of customer_info.customer_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_id
     *
     * @param customerId the value for customer_info.customer_id
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_name
     *
     * @return the value of customer_info.customer_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_name
     *
     * @param customerName the value for customer_info.customer_name
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.identity_card_type
     *
     * @return the value of customer_info.identity_card_type
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Byte getIdentityCardType() {
        return identityCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.identity_card_type
     *
     * @param identityCardType the value for customer_info.identity_card_type
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setIdentityCardType(Byte identityCardType) {
        this.identityCardType = identityCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.identity_card_no
     *
     * @return the value of customer_info.identity_card_no
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getIdentityCardNo() {
        return identityCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.identity_card_no
     *
     * @param identityCardNo the value for customer_info.identity_card_no
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setIdentityCardNo(String identityCardNo) {
        this.identityCardNo = identityCardNo == null ? null : identityCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.mobile_phone
     *
     * @return the value of customer_info.mobile_phone
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Integer getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.mobile_phone
     *
     * @param mobilePhone the value for customer_info.mobile_phone
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setMobilePhone(Integer mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_email
     *
     * @return the value of customer_info.customer_email
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_email
     *
     * @param customerEmail the value for customer_info.customer_email
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.gender
     *
     * @return the value of customer_info.gender
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.gender
     *
     * @param gender the value for customer_info.gender
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.user_point
     *
     * @return the value of customer_info.user_point
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Integer getUserPoint() {
        return userPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.user_point
     *
     * @param userPoint the value for customer_info.user_point
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setUserPoint(Integer userPoint) {
        this.userPoint = userPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.register_time
     *
     * @return the value of customer_info.register_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.register_time
     *
     * @param registerTime the value for customer_info.register_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.birthday
     *
     * @return the value of customer_info.birthday
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.birthday
     *
     * @param birthday the value for customer_info.birthday
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_level
     *
     * @return the value of customer_info.customer_level
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Byte getCustomerLevel() {
        return customerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_level
     *
     * @param customerLevel the value for customer_info.customer_level
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setCustomerLevel(Byte customerLevel) {
        this.customerLevel = customerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.user_money
     *
     * @return the value of customer_info.user_money
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.user_money
     *
     * @param userMoney the value for customer_info.user_money
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.modified_time
     *
     * @return the value of customer_info.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.modified_time
     *
     * @param modifiedTime the value for customer_info.modified_time
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbg.generated Fri Jul 17 15:24:46 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerInfoId=").append(customerInfoId);
        sb.append(", customerId=").append(customerId);
        sb.append(", customerName=").append(customerName);
        sb.append(", identityCardType=").append(identityCardType);
        sb.append(", identityCardNo=").append(identityCardNo);
        sb.append(", mobilePhone=").append(mobilePhone);
        sb.append(", customerEmail=").append(customerEmail);
        sb.append(", gender=").append(gender);
        sb.append(", userPoint=").append(userPoint);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", birthday=").append(birthday);
        sb.append(", customerLevel=").append(customerLevel);
        sb.append(", userMoney=").append(userMoney);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}