package com.online.mall.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   订单主表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_master
 */
public class OrderMaster implements Serializable {
    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   订单编号 yyyymmddnnnnnnnn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Long orderSn;

    /**
     * Database Column Remarks:
     *   下单人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.customer_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   收货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.shipping_user
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private String shippingUser;

    /**
     * Database Column Remarks:
     *   收货人所在省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.province
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Short province;

    /**
     * Database Column Remarks:
     *   收货人所在市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.city
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Short city;

    /**
     * Database Column Remarks:
     *   收货人所在区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.district
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Short district;

    /**
     * Database Column Remarks:
     *   收货人详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.address
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private String address;

    /**
     * Database Column Remarks:
     *   支付方式:1现金,2余额,3网银,4支付宝,5微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.payment_method
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Byte paymentMethod;

    /**
     * Database Column Remarks:
     *   订单金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private BigDecimal orderMoney;

    /**
     * Database Column Remarks:
     *   优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.district_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private BigDecimal districtMoney;

    /**
     * Database Column Remarks:
     *   运费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.shipping_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private BigDecimal shippingMoney;

    /**
     * Database Column Remarks:
     *   支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.payment_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private BigDecimal paymentMoney;

    /**
     * Database Column Remarks:
     *   快递公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.shipping_comp_name
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private String shippingCompName;

    /**
     * Database Column Remarks:
     *   快递单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.shipping_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private String shippingSn;

    /**
     * Database Column Remarks:
     *   下单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.shipping_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Date shippingTime;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Date payTime;

    /**
     * Database Column Remarks:
     *   收货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.receive_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Date receiveTime;

    /**
     * Database Column Remarks:
     *   订单状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Byte orderStatus;

    /**
     * Database Column Remarks:
     *   订单积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_point
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Integer orderPoint;

    /**
     * Database Column Remarks:
     *   发票抬头
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.invoice_title
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private String invoiceTitle;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.modified_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_master
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_id
     *
     * @return the value of order_master.order_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_id
     *
     * @param orderId the value for order_master.order_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_sn
     *
     * @return the value of order_master.order_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_sn
     *
     * @param orderSn the value for order_master.order_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.customer_id
     *
     * @return the value of order_master.customer_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.customer_id
     *
     * @param customerId the value for order_master.customer_id
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_user
     *
     * @return the value of order_master.shipping_user
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public String getShippingUser() {
        return shippingUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_user
     *
     * @param shippingUser the value for order_master.shipping_user
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setShippingUser(String shippingUser) {
        this.shippingUser = shippingUser == null ? null : shippingUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.province
     *
     * @return the value of order_master.province
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.province
     *
     * @param province the value for order_master.province
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.city
     *
     * @return the value of order_master.city
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.city
     *
     * @param city the value for order_master.city
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.district
     *
     * @return the value of order_master.district
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Short getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.district
     *
     * @param district the value for order_master.district
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setDistrict(Short district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.address
     *
     * @return the value of order_master.address
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.address
     *
     * @param address the value for order_master.address
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.payment_method
     *
     * @return the value of order_master.payment_method
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.payment_method
     *
     * @param paymentMethod the value for order_master.payment_method
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_money
     *
     * @return the value of order_master.order_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_money
     *
     * @param orderMoney the value for order_master.order_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.district_money
     *
     * @return the value of order_master.district_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public BigDecimal getDistrictMoney() {
        return districtMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.district_money
     *
     * @param districtMoney the value for order_master.district_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setDistrictMoney(BigDecimal districtMoney) {
        this.districtMoney = districtMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_money
     *
     * @return the value of order_master.shipping_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public BigDecimal getShippingMoney() {
        return shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_money
     *
     * @param shippingMoney the value for order_master.shipping_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setShippingMoney(BigDecimal shippingMoney) {
        this.shippingMoney = shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.payment_money
     *
     * @return the value of order_master.payment_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public BigDecimal getPaymentMoney() {
        return paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.payment_money
     *
     * @param paymentMoney the value for order_master.payment_money
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setPaymentMoney(BigDecimal paymentMoney) {
        this.paymentMoney = paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_comp_name
     *
     * @return the value of order_master.shipping_comp_name
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public String getShippingCompName() {
        return shippingCompName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_comp_name
     *
     * @param shippingCompName the value for order_master.shipping_comp_name
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setShippingCompName(String shippingCompName) {
        this.shippingCompName = shippingCompName == null ? null : shippingCompName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_sn
     *
     * @return the value of order_master.shipping_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public String getShippingSn() {
        return shippingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_sn
     *
     * @param shippingSn the value for order_master.shipping_sn
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setShippingSn(String shippingSn) {
        this.shippingSn = shippingSn == null ? null : shippingSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.create_time
     *
     * @return the value of order_master.create_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.create_time
     *
     * @param createTime the value for order_master.create_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_time
     *
     * @return the value of order_master.shipping_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Date getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_time
     *
     * @param shippingTime the value for order_master.shipping_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setShippingTime(Date shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.pay_time
     *
     * @return the value of order_master.pay_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.pay_time
     *
     * @param payTime the value for order_master.pay_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.receive_time
     *
     * @return the value of order_master.receive_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.receive_time
     *
     * @param receiveTime the value for order_master.receive_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_status
     *
     * @return the value of order_master.order_status
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_status
     *
     * @param orderStatus the value for order_master.order_status
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_point
     *
     * @return the value of order_master.order_point
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Integer getOrderPoint() {
        return orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_point
     *
     * @param orderPoint the value for order_master.order_point
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setOrderPoint(Integer orderPoint) {
        this.orderPoint = orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.invoice_title
     *
     * @return the value of order_master.invoice_title
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.invoice_title
     *
     * @param invoiceTitle the value for order_master.invoice_title
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.modified_time
     *
     * @return the value of order_master.modified_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.modified_time
     *
     * @param modifiedTime the value for order_master.modified_time
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Tue Jul 07 15:40:19 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", customerId=").append(customerId);
        sb.append(", shippingUser=").append(shippingUser);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", address=").append(address);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", orderMoney=").append(orderMoney);
        sb.append(", districtMoney=").append(districtMoney);
        sb.append(", shippingMoney=").append(shippingMoney);
        sb.append(", paymentMoney=").append(paymentMoney);
        sb.append(", shippingCompName=").append(shippingCompName);
        sb.append(", shippingSn=").append(shippingSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderPoint=").append(orderPoint);
        sb.append(", invoiceTitle=").append(invoiceTitle);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}