package com.online.mall.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table permission_info
 */
public class PermissionInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.permission_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Long permissionId;

    /**
     * Database Column Remarks:
     *   父级权限id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.pid
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Long pid;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.name
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String name;

    /**
     * Database Column Remarks:
     *   权限值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.value
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String value;

    /**
     * Database Column Remarks:
     *   图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.icon
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   权限类型：0->目录；1->菜单；2->按钮（接口绑定权限）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.type
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   前端资源路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.uri
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private String uri;

    /**
     * Database Column Remarks:
     *   启用状态；0->禁用；1->启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.status
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.create_time
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_info.sort
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.permission_id
     *
     * @return the value of permission_info.permission_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.permission_id
     *
     * @param permissionId the value for permission_info.permission_id
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.pid
     *
     * @return the value of permission_info.pid
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.pid
     *
     * @param pid the value for permission_info.pid
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.name
     *
     * @return the value of permission_info.name
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.name
     *
     * @param name the value for permission_info.name
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.value
     *
     * @return the value of permission_info.value
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.value
     *
     * @param value the value for permission_info.value
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.icon
     *
     * @return the value of permission_info.icon
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.icon
     *
     * @param icon the value for permission_info.icon
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.type
     *
     * @return the value of permission_info.type
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.type
     *
     * @param type the value for permission_info.type
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.uri
     *
     * @return the value of permission_info.uri
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.uri
     *
     * @param uri the value for permission_info.uri
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.status
     *
     * @return the value of permission_info.status
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.status
     *
     * @param status the value for permission_info.status
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.create_time
     *
     * @return the value of permission_info.create_time
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.create_time
     *
     * @param createTime the value for permission_info.create_time
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_info.sort
     *
     * @return the value of permission_info.sort
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_info.sort
     *
     * @param sort the value for permission_info.sort
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_info
     *
     * @mbg.generated Fri Jul 17 15:24:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionId=").append(permissionId);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", value=").append(value);
        sb.append(", icon=").append(icon);
        sb.append(", type=").append(type);
        sb.append(", uri=").append(uri);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}