package com.online.mall.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_info
 */
public class ProductInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   商品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String productCode;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   国条码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.bar_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String barCode;

    /**
     * Database Column Remarks:
     *   品牌表的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.brand_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Integer brandId;

    /**
     * Database Column Remarks:
     *   一级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.one_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short oneCategoryId;

    /**
     * Database Column Remarks:
     *   二级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.two_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short twoCategoryId;

    /**
     * Database Column Remarks:
     *   三级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.three_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short threeCategoryId;

    /**
     * Database Column Remarks:
     *   商品的供应商id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.supplier_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Integer supplierId;

    /**
     * Database Column Remarks:
     *   商品销售价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   商品加权平均成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.average_cost
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private BigDecimal averageCost;

    /**
     * Database Column Remarks:
     *   上下架状态:0下架1上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.publish_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Byte publishStatus;

    /**
     * Database Column Remarks:
     *   审核状态:0未审核,1已审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.audit_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Byte auditStatus;

    /**
     * Database Column Remarks:
     *   商品重量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.weight
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Float weight;

    /**
     * Database Column Remarks:
     *   商品长度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.length
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Float length;

    /**
     * Database Column Remarks:
     *   商品高度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.heigh
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Float heigh;

    /**
     * Database Column Remarks:
     *   商品宽度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.width
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Float width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.color_type
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String colorType;

    /**
     * Database Column Remarks:
     *   生产日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.production_date
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Date productionDate;

    /**
     * Database Column Remarks:
     *   商品有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.shelf_life
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Integer shelfLife;

    /**
     * Database Column Remarks:
     *   商品录入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.indate
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Date indate;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Date modifiedTime;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.descript
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_code
     *
     * @return the value of product_info.product_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_code
     *
     * @param productCode the value for product_info.product_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.bar_code
     *
     * @return the value of product_info.bar_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.bar_code
     *
     * @param barCode the value for product_info.bar_code
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.brand_id
     *
     * @return the value of product_info.brand_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.brand_id
     *
     * @param brandId the value for product_info.brand_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.one_category_id
     *
     * @return the value of product_info.one_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getOneCategoryId() {
        return oneCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.one_category_id
     *
     * @param oneCategoryId the value for product_info.one_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setOneCategoryId(Short oneCategoryId) {
        this.oneCategoryId = oneCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.two_category_id
     *
     * @return the value of product_info.two_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getTwoCategoryId() {
        return twoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.two_category_id
     *
     * @param twoCategoryId the value for product_info.two_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setTwoCategoryId(Short twoCategoryId) {
        this.twoCategoryId = twoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.three_category_id
     *
     * @return the value of product_info.three_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getThreeCategoryId() {
        return threeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.three_category_id
     *
     * @param threeCategoryId the value for product_info.three_category_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setThreeCategoryId(Short threeCategoryId) {
        this.threeCategoryId = threeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.supplier_id
     *
     * @return the value of product_info.supplier_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.supplier_id
     *
     * @param supplierId the value for product_info.supplier_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.average_cost
     *
     * @return the value of product_info.average_cost
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public BigDecimal getAverageCost() {
        return averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.average_cost
     *
     * @param averageCost the value for product_info.average_cost
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setAverageCost(BigDecimal averageCost) {
        this.averageCost = averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.publish_status
     *
     * @return the value of product_info.publish_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Byte getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.publish_status
     *
     * @param publishStatus the value for product_info.publish_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setPublishStatus(Byte publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.audit_status
     *
     * @return the value of product_info.audit_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.audit_status
     *
     * @param auditStatus the value for product_info.audit_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.weight
     *
     * @return the value of product_info.weight
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.weight
     *
     * @param weight the value for product_info.weight
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.length
     *
     * @return the value of product_info.length
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.length
     *
     * @param length the value for product_info.length
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.heigh
     *
     * @return the value of product_info.heigh
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Float getHeigh() {
        return heigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.heigh
     *
     * @param heigh the value for product_info.heigh
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setHeigh(Float heigh) {
        this.heigh = heigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.width
     *
     * @return the value of product_info.width
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Float getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.width
     *
     * @param width the value for product_info.width
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWidth(Float width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.color_type
     *
     * @return the value of product_info.color_type
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getColorType() {
        return colorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.color_type
     *
     * @param colorType the value for product_info.color_type
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setColorType(String colorType) {
        this.colorType = colorType == null ? null : colorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.production_date
     *
     * @return the value of product_info.production_date
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.production_date
     *
     * @param productionDate the value for product_info.production_date
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.shelf_life
     *
     * @return the value of product_info.shelf_life
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Integer getShelfLife() {
        return shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.shelf_life
     *
     * @param shelfLife the value for product_info.shelf_life
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setShelfLife(Integer shelfLife) {
        this.shelfLife = shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.indate
     *
     * @return the value of product_info.indate
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.indate
     *
     * @param indate the value for product_info.indate
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.modified_time
     *
     * @return the value of product_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.modified_time
     *
     * @param modifiedTime the value for product_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.descript
     *
     * @return the value of product_info.descript
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.descript
     *
     * @param descript the value for product_info.descript
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productCode=").append(productCode);
        sb.append(", productName=").append(productName);
        sb.append(", barCode=").append(barCode);
        sb.append(", brandId=").append(brandId);
        sb.append(", oneCategoryId=").append(oneCategoryId);
        sb.append(", twoCategoryId=").append(twoCategoryId);
        sb.append(", threeCategoryId=").append(threeCategoryId);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", price=").append(price);
        sb.append(", averageCost=").append(averageCost);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", auditStatus=").append(auditStatus);
        sb.append(", weight=").append(weight);
        sb.append(", length=").append(length);
        sb.append(", heigh=").append(heigh);
        sb.append(", width=").append(width);
        sb.append(", colorType=").append(colorType);
        sb.append(", productionDate=").append(productionDate);
        sb.append(", shelfLife=").append(shelfLife);
        sb.append(", indate=").append(indate);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", descript=").append(descript);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}