package com.online.mall.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   仓库信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table warehouse_info
 */
public class WarehouseInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   仓库ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.w_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short wId;

    /**
     * Database Column Remarks:
     *   仓库编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.warehouse_sn
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String warehouseSn;

    /**
     * Database Column Remarks:
     *   仓库名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.warehouse_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String warehouseName;

    /**
     * Database Column Remarks:
     *   仓库电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.warehouse_phone
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String warehousePhone;

    /**
     * Database Column Remarks:
     *   仓库联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.contact
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String contact;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.province
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.city
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.district
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Short district;

    /**
     * Database Column Remarks:
     *   仓库地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.address
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private String address;

    /**
     * Database Column Remarks:
     *   仓库状态:0禁用,1启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.warehouse_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Byte warehouseStatus;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_info
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.w_id
     *
     * @return the value of warehouse_info.w_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getwId() {
        return wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.w_id
     *
     * @param wId the value for warehouse_info.w_id
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setwId(Short wId) {
        this.wId = wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.warehouse_sn
     *
     * @return the value of warehouse_info.warehouse_sn
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getWarehouseSn() {
        return warehouseSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.warehouse_sn
     *
     * @param warehouseSn the value for warehouse_info.warehouse_sn
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWarehouseSn(String warehouseSn) {
        this.warehouseSn = warehouseSn == null ? null : warehouseSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.warehouse_name
     *
     * @return the value of warehouse_info.warehouse_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.warehouse_name
     *
     * @param warehouseName the value for warehouse_info.warehouse_name
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.warehouse_phone
     *
     * @return the value of warehouse_info.warehouse_phone
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getWarehousePhone() {
        return warehousePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.warehouse_phone
     *
     * @param warehousePhone the value for warehouse_info.warehouse_phone
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWarehousePhone(String warehousePhone) {
        this.warehousePhone = warehousePhone == null ? null : warehousePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.contact
     *
     * @return the value of warehouse_info.contact
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.contact
     *
     * @param contact the value for warehouse_info.contact
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.province
     *
     * @return the value of warehouse_info.province
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.province
     *
     * @param province the value for warehouse_info.province
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.city
     *
     * @return the value of warehouse_info.city
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.city
     *
     * @param city the value for warehouse_info.city
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.district
     *
     * @return the value of warehouse_info.district
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Short getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.district
     *
     * @param district the value for warehouse_info.district
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setDistrict(Short district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.address
     *
     * @return the value of warehouse_info.address
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.address
     *
     * @param address the value for warehouse_info.address
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.warehouse_status
     *
     * @return the value of warehouse_info.warehouse_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Byte getWarehouseStatus() {
        return warehouseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.warehouse_status
     *
     * @param warehouseStatus the value for warehouse_info.warehouse_status
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setWarehouseStatus(Byte warehouseStatus) {
        this.warehouseStatus = warehouseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_info.modified_time
     *
     * @return the value of warehouse_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_info.modified_time
     *
     * @param modifiedTime the value for warehouse_info.modified_time
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_info
     *
     * @mbg.generated Tue Jul 07 09:52:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wId=").append(wId);
        sb.append(", warehouseSn=").append(warehouseSn);
        sb.append(", warehouseName=").append(warehouseName);
        sb.append(", warehousePhone=").append(warehousePhone);
        sb.append(", contact=").append(contact);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", address=").append(address);
        sb.append(", warehouseStatus=").append(warehouseStatus);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}